$response = Invoke-WebRequest -Uri http://localhost:5000/api/create-session -Method POST -UseBasicParsing
$json = $response.Content | ConvertFrom-Json

Write-Host "🎉 EMERGENCY SESSION CREATED!"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""
Write-Host "Session ID: $($json.sessionId)"
Write-Host "Agent ID:   $($json.agentId)"
Write-Host "Token:      $($json.token)"
Write-Host ""
Write-Host "🌐 NEXT STEPS:"
Write-Host ""
Write-Host "1. Open your browser console (F12)"
Write-Host ""
Write-Host "2. Copy and paste these commands:"
Write-Host ""
Write-Host "localStorage.setItem('agent_session', '$($json.sessionId)');"
Write-Host "localStorage.setItem('agent_token', '$($json.token)');"
Write-Host "localStorage.setItem('agent_id', '$($json.agentId)');"
Write-Host ""
Write-Host "3. Navigate to:"
Write-Host ""
Write-Host "http://localhost:5173/live/agent/$($json.sessionId)"
Write-Host ""
Write-Host "4. Press Enter to refresh"
Write-Host ""
Write-Host "✨ Your agent is ready to use!"
