# Nixpacks configuration for worker service
[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmds = [
  "npm install",
  "npx playwright install-deps chromium"
]

[start]
cmd = "npm start"

